export default {
    hairCare: "a[href*='product/category&path=']",
    headerText: 'h1 .maintext',
    productName: '.fixed_wrapper .prdocutname',
    productThumbnail: '@productThumbnail',
    category1: "a[href*='product/category&path=']",
    conditioner: ':nth-child(1) > .mt10 > a',
    seaweedConditioner: ':nth-child(1) > .thumbnail > :nth-child(1) > img',
    productQuanttity1: '#product_quantity',
    cart: '.cart',
    remove: ':nth-child(7) > .btn > .fa',
    book: "a[href*='product/category&path=']",
    paperBackItem: 'ul.thumbnails > :nth-child(2) > :nth-child(1) > img',
    product: ':nth-child(3) > .thumbnail > :nth-child(1) > img',
    productQuantity2: '#product_quantity',
    cartCheckout: '#cart_checkout1',
    checkout: '#checkout_btn',
    continue: '.mb40 > .btn',
    welcomeMessage: '.welcome_msg > h4',
    account: '#main_menu_top > [data-id="menu_account',
    register: '.newcustomer',
    continueAsNewCustomer: '#accountFrm > fieldset > .btn',
    firstName: '#AccountFrm_firstname',
    lastName: '#AccountFrm_lastname',
    email: '#AccountFrm_email',
    telephoneNumber: '#AccountFrm_telephone',
    faxNumber: '#AccountFrm_fax',
    companyName: '#AccountFrm_company',
    addressNumber1: '#AccountFrm_address_1',
    addressNumber2: '#AccountFrm_address_1',
    cityName: '#AccountFrm_city',
    zoneId: '#AccountFrm_zone_id',
    postCode: '#AccountFrm_postcode',
    countryId: '#AccountFrm_country_id',
    loginName: '#AccountFrm_loginname',
    password: '#AccountFrm_password',
    confirmPassword: '#AccountFrm_confirm',
    newsletter1: '#AccountFrm_newsletter1',
    newsletter2: '#AccountFrm_newsletter1',
    agree: "input[name='agree']",
    continueAfterReadPrivacy: '.col-md-2 > .btn',
    subTextForVerification: '.subtext',
    firstNameContactForm: '#ContactUsFrm_first_name',
    emailForContactForm: '#ContactUsFrm_email',
    emailForContactForm2: '#ContactUsFrm_email',
    enquiryForContactForm: '#ContactUsFrm_enquiry',
    submit: "button[title='Submit']",
    responseMessageText: '.mb40 > :nth-child(3)'


  };
  